### ISSUE TITLE
support incrementing existing version qualifier

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-version-manipulator#2]
If a qualified version is encountered, it should be incremented. Currently, a new version qualifier will be appended to it if the existing qualifier doesn't match the one given in the configuration.

NOTE: It's not clear that existing qualified versions of parent POMs should be incremented. Probably need to accommodate both options using a flag or similar.

**Comment by rnc** [comment]
Closing ; tool replaced by https://github.com/release-engineering/pom-manipulation-ext
